const $=id=>document.getElementById(id);const fmt=n=>new Intl.NumberFormat('ru-RU').format(Number(n)||0);let config=null,adminCaptchaWidget=null,adminCaptchaToken=null,currentPage=1;async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options});let d=null;try{d=await r.json()}catch{}if(!r.ok){const e=new Error(d?.detail||`HTTP ${r.status}`);e.status=r.status;throw e}return d}
async function init(){config=await api('/api/config').catch(()=>({captcha_enabled:false,turnstile_site_key:''}));populateCategories();const me=await api('/api/admin/me');if(me.authenticated)showDashboard();else setupLoginCaptcha();$('loginForm').addEventListener('submit',login);$('logoutBtn').addEventListener('click',logout);$('schoolForm').addEventListener('submit',addSchool);$('schoolSearch').addEventListener('input',()=>{currentPage=1;loadSchools()});$('schoolPrev').addEventListener('click',()=>{if(currentPage>1){currentPage--;loadSchools()}});$('schoolNext').addEventListener('click',()=>{currentPage++;loadSchools()})}
function populateCategories(){[['general_schools','Общеобразовательные школы'],['lyceums_gymnasiums','Лицеи и гимназии'],['colleges','Колледжи и техникумы'],['universities','ВУЗы'],['private_schools','Частные школы'],['boarding_schools','Школы-интернаты']].forEach(([v,l])=>{const o=document.createElement('option');o.value=v;o.textContent=l;$('schoolCategoryInput').appendChild(o)})}
function setupLoginCaptcha(){if(!config?.captcha_enabled||!config.turnstile_site_key)return;const mount=()=>{if(!window.turnstile||adminCaptchaWidget!==null)return;adminCaptchaWidget=window.turnstile.render('#adminCaptcha',{sitekey:config.turnstile_site_key,theme:'dark',callback:t=>adminCaptchaToken=t,'expired-callback':()=>adminCaptchaToken=null})};window.turnstile?mount():setTimeout(mount,700)}
async function login(e){e.preventDefault();$('loginError').textContent='';try{await api('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('loginUsername').value.trim(),password:$('loginPassword').value,captcha_token:adminCaptchaToken})});showDashboard()}catch(err){$('loginError').textContent=err.message||'Ошибка входа';if(adminCaptchaWidget!==null){try{window.turnstile.reset(adminCaptchaWidget)}catch{}adminCaptchaToken=null}}}
async function showDashboard(){ $('loginCard').classList.add('hidden');$('dashboard').classList.remove('hidden');await loadDashboard()}
async function logout(){await api('/api/admin/logout',{method:'POST'}).catch(()=>{});location.reload()}
async function loadDashboard(){const d=await api('/api/admin/dashboard');renderStats(d);renderAbuse(d.abuse||[]);await loadSchools()}
function renderStats(d){$('adminStats').innerHTML=`<div class="stat"><span>Учебных заведений</span><strong>${fmt(d.schools_count)}</strong></div><div class="stat"><span>Из исходного списка</span><strong>${fmt(d.national_schools)}</strong></div><div class="stat"><span>Реальных кликов</span><strong>${fmt(d.total_clicks)}</strong></div><div class="stat"><span>Сигналов абьюза</span><strong>${fmt(d.abuse_events)}</strong></div>`}
function renderAbuse(items){const root=$('abuseList');if(!items.length){root.innerHTML='<div class="empty">Подозрительных событий пока нет.</div>';return}root.innerHTML=items.map(i=>`<article class="abuse-item"><div class="abuse-top"><strong>${escapeHtml(i.event_type)}</strong><time>${new Date(i.created_at).toLocaleString('ru-RU')}</time></div><div class="abuse-meta">ID: <code>${escapeHtml(i.identity||'—')}</code><br>IP-сеть: ${escapeHtml(i.ip_prefix||'—')}</div><p>${escapeHtml(i.details||'')}</p>${i.identity?`<button class="mini danger" data-block="${escapeHtml(i.identity)}">Заблокировать</button>`:''}</article>`).join('');root.querySelectorAll('[data-block]').forEach(b=>b.addEventListener('click',async()=>{await api('/api/admin/block',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identity_hash:b.dataset.block,reason:'Заблокировано администратором'})});loadDashboard()}))}
async function loadSchools(){const q=$('schoolSearch').value.trim();const d=await api(`/api/admin/schools?page=${currentPage}&per_page=100&q=${encodeURIComponent(q)}`);renderSchools(d.items||[]);$('schoolPage').textContent=`${d.page} / ${Math.max(1,Math.ceil(d.total/d.per_page))}`;$('schoolPrev').disabled=d.page<=1;$('schoolNext').disabled=d.page>=Math.ceil(d.total/d.per_page)}
function renderSchools(items){const root=$('schoolsList');root.innerHTML=items.map(s=>`<div class="school-row"><div><strong>${escapeHtml(s.name)}</strong><span>${escapeHtml(s.city)}, ${escapeHtml(s.region||'Россия')} · ${escapeHtml(s.category_label)}</span></div><div class="school-side"><b>${fmt(s.clicks)}</b><small>${s.origin==='bundled'?'Калининград · фото в проекте':s.image_source==='upload'?'Фото загружено':'Без фото'}</small></div></div>`).join('')||'<div class="empty">Ничего не найдено.</div>'}
async function addSchool(e){e.preventDefault();$('schoolFormStatus').textContent='Сохраняем…';const f=new FormData();f.set('name',$('schoolNameInput').value.trim());f.set('country',$('schoolCountryInput').value.trim()||'Россия');f.set('region',$('schoolRegionInput').value.trim());f.set('city',$('schoolCityInput').value.trim());f.set('category',$('schoolCategoryInput').value);const file=$('schoolPhotoInput').files[0];if(file)f.set('photo',file);try{const d=await api('/api/admin/schools',{method:'POST',body:f});$('schoolFormStatus').textContent=`Готово: ${d.school.name} добавлена.`;$('schoolForm').reset();$('schoolCountryInput').value='Россия';currentPage=1;await loadDashboard()}catch(err){$('schoolFormStatus').textContent=err.message||'Не удалось добавить школу.'}}
function escapeHtml(v){return String(v).replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}init().catch(e=>$('loginError').textContent=e.message||'Ошибка загрузки');