const state={
 cities:[], city:null, category:null, selectedSchoolId:localStorage.getItem('bitva_school_id')||null,
 selectedCityName:null, pendingClicks:0, sessionClicks:0, clickEnabled:false, captchaEnabled:false,
 turnstileWidgetId:null, turnstileToken:null, audio:null, sending:false, leaderboardScope:'schools', lastCounts:new Map(),
};
const $=id=>document.getElementById(id);
const fmt=n=>new Intl.NumberFormat('ru-RU').format(Number(n)||0);
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2400)}
function animateNumber(el,target,duration=350){if(!el)return;const from=Number(el.dataset.value ?? (String(el.textContent).replace(/\D/g,'') || 0)),to=Number(target)||0;if(from===to){el.textContent=fmt(to);el.dataset.value=String(to);return}const st=performance.now();el.dataset.value=String(to);const tick=t=>{const p=Math.min(1,(t-st)/duration),e=1-Math.pow(1-p,3);el.textContent=fmt(Math.round(from+(to-from)*e));if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)}
async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options});let d=null;try{d=await r.json()}catch{}if(!r.ok){const e=new Error(d?.detail||`HTTP ${r.status}`);e.status=r.status;e.data=d;throw e}return d}
function plural(n,a,b,c){const x=Math.abs(Number(n))%100,y=x%10;if(x>=11&&x<=19)return c;if(y===1)return a;if(y>=2&&y<=4)return b;return c}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function bindEvents(){
 $('pathRegion').onclick=renderCitySelection;$('pathCity').onclick=()=>state.city&&renderCategorySelection(state.city);$('pathCategory').onclick=()=>state.city&&renderCategorySelection(state.city);
 $('leaderboardToggle').onclick=toggleLeaderboard;$('rankSchoolsBtn').onclick=()=>setLeaderboardScope('schools');$('rankCitiesBtn').onclick=()=>setLeaderboardScope('cities');
 $('aboutBtn').onclick=openAbout;$('changeSchoolBtn').onclick=backToSelection;$('heroClickArea').addEventListener('pointerdown',handleClick,{passive:true});
 document.querySelectorAll('[data-close]').forEach(e=>e.onclick=()=>closeSheet(e.dataset.close));$('captchaClose').onclick=()=>closeCaptchaGate(true);
}
async function bootstrap(){bindEvents();try{const [cfg,cities,session]=await Promise.all([api('/api/config'),api('/api/cities'),api('/api/session')]);state.captchaEnabled=!!cfg.captcha_enabled;state.cities=cities.cities||[];state.sessionClicks=Number(session.clicks_minute||0);state.city=null;renderCitySelection();if(state.selectedSchoolId){try{const sh=await api('/api/schools/'+encodeURIComponent(state.selectedSchoolId));$('rememberedSchoolBtn').textContent=`Продолжить с «${sh.name}»`;$('rememberedSchoolBtn').classList.remove('hidden');$('rememberedSchoolBtn').onclick=()=>selectSchool(sh.id)}catch{}}}catch(e){console.error(e);toast('Не удалось загрузить сайт')}
 refreshLeaderboard();refreshStats();setInterval(()=>refreshLeaderboard(),5000);setInterval(()=>refreshStats(),3000);setInterval(()=>sendClicks(),5000);setInterval(()=>heartbeat(),15000);window.addEventListener('pagehide',flushBeacon);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flushBeacon()})}
function clearGrid(){const g=$('categoryGrid');g.innerHTML='';return g}
function renderCitySelection(){state.city=null;state.category=null;$('pathRegion').classList.add('active');$('pathCity').classList.remove('active');$('pathCity').disabled=true;$('pathCity').textContent='Город';$('pathCategory').classList.remove('active');$('pathCategory').disabled=true;$('pathCategory').textContent='Категория';const grid=clearGrid();const intro=document.createElement('div');intro.className='selection-intro';intro.innerHTML='<div class="eyebrow">РОССИЯ</div><h2>Выберите город</h2><p>Выберите город, категорию и учебное заведение.</p>';grid.appendChild(intro);state.cities.forEach(city=>{const b=document.createElement('button');b.className='category-card region-card';b.innerHTML=`<span class="card-kicker">РОССИЯ</span><strong>${escapeHtml(city.name)}</strong><span>${fmt(city.count)} ${plural(city.count,'учебное заведение','учебных заведения','учебных заведений')}</span>`;b.onclick=()=>renderCategorySelection(city);grid.appendChild(b)})}
async function renderCategorySelection(city){state.city=city;state.category=null;$('pathRegion').classList.remove('active');$('pathCity').classList.add('active');$('pathCity').disabled=false;$('pathCity').textContent=city.name;$('pathCategory').classList.remove('active');$('pathCategory').disabled=true;$('pathCategory').textContent='Категория';const grid=clearGrid();const intro=document.createElement('div');intro.className='selection-intro';intro.innerHTML=`<div class="eyebrow">РОССИЯ · ${escapeHtml(city.name)}</div><h2>Выберите категорию</h2><p>Загружаются только данные выбранного города.</p>`;grid.appendChild(intro);try{const d=await api('/api/cities/'+encodeURIComponent(city.name)+'/categories');(d.categories||[]).forEach(cat=>{const b=document.createElement('button');b.className='category-card category-wide';b.innerHTML=`<strong>${escapeHtml(cat.name)}</strong><span>${fmt(cat.schools.length)} ${plural(cat.schools.length,'вариант','варианта','вариантов')}</span><span class="arrow">→</span>`;b.onclick=()=>renderSchoolSelection(cat);grid.appendChild(b)})}catch(e){toast(e.message||'Не удалось загрузить город')}}
function renderSchoolSelection(cat){state.category=cat;$('pathCategory').classList.add('active');$('pathCategory').disabled=false;$('pathCategory').textContent=cat.name;const grid=clearGrid();const intro=document.createElement('div');intro.className='selection-intro';intro.innerHTML=`<div class="eyebrow">${escapeHtml(cat.name)}</div><h2>${escapeHtml(state.city.name)}</h2><p>${fmt(cat.schools.length)} заведений. Фото добавляются вручную через админку.</p>`;grid.appendChild(intro);(cat.schools||[]).forEach(s=>{const b=document.createElement('button');b.className='category-card school-card';b.innerHTML=`<div><strong>${escapeHtml(s.name)}</strong><span>${escapeHtml(s.region||'Россия')}</span></div><span class="arrow">→</span>`;b.onclick=()=>selectSchool(s.id);grid.appendChild(b)})}
async function selectSchool(id){try{const sh=await api('/api/schools/'+encodeURIComponent(id));state.selectedSchoolId=id;state.selectedCityName=sh.city;localStorage.setItem('bitva_school_id',id);state.pendingClicks=0;state.clickEnabled=!state.captchaEnabled;$('selectionView').classList.add('hidden');$('schoolView').classList.remove('hidden');$('categoryLabel').textContent=`${sh.city} · ${sh.category_label}`;$('heroLocation').textContent=`РОССИЯ · ${sh.region||sh.city}`;$('schoolName').textContent=sh.name;$('heroMobileSource').srcset=sh.images.mobile;$('heroImage').src=sh.images.desktop;$('heroImage').alt=sh.name;$('sessionClicks').textContent=fmt(state.sessionClicks);$('clickLocked').textContent=state.captchaEnabled?'Сначала пройди проверку':'Клики доступны';$('clickLocked').classList.toggle('hidden',state.clickEnabled);refreshLeaderboard();refreshStats();if(state.captchaEnabled)openCaptchaGate(false)}catch(e){toast(e.message||'Не удалось открыть учебное заведение')}}
function backToSelection(){flushBeacon();closeSheet('leaderboard');closeSheet('about');closeCaptchaGate(true);$('schoolView').classList.add('hidden');$('selectionView').classList.remove('hidden');renderCitySelection()}
function handleClick(event){if(!state.selectedSchoolId)return;if(!state.clickEnabled){openCaptchaGate(false);return}state.pendingClicks++;state.sessionClicks++;animateNumber($('sessionClicks'),state.sessionClicks);spawnFloat(event);playClickSound()}
function spawnFloat(event){const a=$('heroClickArea').getBoundingClientRect(),x=Math.max(14,Math.min(a.width-14,event.clientX-a.left)),y=Math.max(14,Math.min(a.height-14,event.clientY-a.top));const el=document.createElement('span');el.className='float-number';el.textContent='+1';el.style.left=`${x}px`;el.style.top=`${y}px`;$('floatLayer').appendChild(el);el.addEventListener('animationend',()=>el.remove(),{once:true})}
function playClickSound(){try{if(!state.audio)state.audio=new Audio('/assets/branding/sounds/pop.mp3');state.audio.currentTime=0;state.audio.play()?.catch(()=>{})}catch{}}
function makeRequestId(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(36).slice(2)}`}
async function sendClicks(){if(!state.pendingClicks||!state.selectedSchoolId||state.sending||!state.clickEnabled)return;state.sending=true;const batch=Math.min(state.pendingClicks,800);try{const d=await api('/api/clicks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({school_id:state.selectedSchoolId,clicks:batch,request_id:makeRequestId()})});state.pendingClicks=Math.max(0,state.pendingClicks-batch);const rejected=Number(d.rejected||0),accepted=Number(d.accepted||0);if(rejected){state.sessionClicks=Math.max(0,state.sessionClicks-rejected);animateNumber($('sessionClicks'),state.sessionClicks);toast(`Засчитано ${fmt(accepted)} · лимит ${fmt(d.limit_per_minute||800)}/мин`)}refreshLeaderboard()}catch(e){if(e.status===403&&/CAPTCHA/i.test(e.message)){state.clickEnabled=false;openCaptchaGate(false)}else if(e.status===429){toast(e.message||'Слишком много активности')}else if(e.status===403){state.clickEnabled=false;toast(e.message||'Клики заблокированы')}}finally{state.sending=false}}
function flushBeacon(){if(!state.pendingClicks||!state.selectedSchoolId||!navigator.sendBeacon||!state.clickEnabled)return;const batch=Math.min(state.pendingClicks,800),body=JSON.stringify({school_id:state.selectedSchoolId,clicks:batch,request_id:makeRequestId()}),blob=new Blob([body],{type:'application/json'});if(navigator.sendBeacon('/api/clicks',blob))state.pendingClicks=Math.max(0,state.pendingClicks-batch)}
async function heartbeat(){try{await api('/api/heartbeat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({school_id:state.selectedSchoolId})})}catch(e){if(e.status===403)state.clickEnabled=false}}
function toggleLeaderboard(){const open=$('leaderboardSheet').classList.contains('open');open?closeSheet('leaderboard'):openSheet('leaderboard')}
function openSheet(name){const el=$(name==='leaderboard'?'leaderboardSheet':'aboutSheet');el.classList.add('open');el.setAttribute('aria-hidden','false');if(name==='leaderboard'){setTimeout(scrollToMine,120)}}
function closeSheet(name){const el=$(name==='leaderboard'?'leaderboardSheet':'aboutSheet');el.classList.remove('open');el.setAttribute('aria-hidden','true')}
async function refreshLeaderboard(){try{const d=await api(`/api/leaderboard?scope=${state.leaderboardScope}&school_id=${encodeURIComponent(state.selectedSchoolId||'')}`);const first=snapshotLeaderboardRows();state.lastCounts=state.lastCounts||new Map();const mine=d.mine;let items=[...(d.items||[])];if(mine&&!items.some(x=>x.id===mine.id))items.push({...mine});renderLeaderboardRows(items,first);const leader=(d.items||[])[0];if(leader){$('leaderName').textContent=leader.name;animateNumber($('leaderClicks'),leader.clicks)}$('myRank').textContent=mine?`#${mine.rank}`:'—';const cityMode=state.leaderboardScope==='cities';$('leaderboardTitle').textContent=cityMode?'Кто сейчас впереди по городам':'Кто сейчас впереди';$('leaderboardSubtitle').textContent=cityMode?'Города России соревнуются по реальным засчитанным кликам.':'Школы соревнуются по реальным засчитанным кликам.';document.querySelectorAll('.rank-tab').forEach((b,i)=>{const active=cityMode?i===1:i===0;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});state.lastCounts=new Map(items.map(x=>[x.id,x.clicks]))}catch(e){console.error(e)}}
function setLeaderboardScope(scope){if(scope===state.leaderboardScope){refreshLeaderboard();return}state.leaderboardScope=scope;state.lastCounts.clear();refreshLeaderboard()}
function snapshotLeaderboardRows(){const m=new Map();$('leaderboardList').querySelectorAll('.leader-row').forEach(r=>m.set(r.dataset.id,r.getBoundingClientRect()));return m}
function animateLeaderboardReorder(first){if(!first.size||!Element.prototype.animate)return;$('leaderboardList').querySelectorAll('.leader-row').forEach(r=>{const a=first.get(r.dataset.id);if(!a)return;const b=r.getBoundingClientRect(),dx=a.left-b.left,dy=a.top-b.top;if(Math.abs(dx)>1||Math.abs(dy)>1)r.animate([{transform:`translate3d(${dx}px,${dy}px,0)`},{transform:'translate3d(0,0,0)'}],{duration:420,easing:'cubic-bezier(.2,.8,.2,1)'})})}
function renderLeaderboardRows(items,first){const list=$('leaderboardList'),wanted=new Set(items.map(x=>x.id));[...list.children].forEach(el=>{if(!wanted.has(el.dataset.id))el.remove()});const existing=new Map([...list.children].map(x=>[x.dataset.id,x]));items.forEach(item=>{let r=existing.get(item.id);if(!r){r=document.createElement('div');r.className='leader-row';r.dataset.id=item.id;r.innerHTML='<div class="leader-rank"></div><div><div class="leader-name"></div><div class="leader-meta"></div></div><div class="leader-count"></div>'}const active=state.leaderboardScope==='schools'?item.id===state.selectedSchoolId:(item.kind==='city'&&item.name===state.selectedCityName);r.classList.toggle('active',active);r.querySelector('.leader-rank').textContent=item.rank;r.querySelector('.leader-name').textContent=item.name;r.querySelector('.leader-meta').textContent=state.leaderboardScope==='cities'?`${item.school_count||0} школ · Россия`:`${item.city} · ${item.region}`;r.querySelector('.leader-count').textContent=`${fmt(item.clicks)} кликов`;list.appendChild(r)});animateLeaderboardReorder(first);}
function scrollToMine(){const id=state.leaderboardScope==='cities'&&state.selectedCityName?`city:${state.selectedCityName}`:state.selectedSchoolId;const row=$('leaderboardList').querySelector(`[data-id="${CSS.escape(id||'')}"]`);row?.scrollIntoView({block:'center',behavior:'smooth'})}
function showLeaderboardDelta(delta){const e=$('leaderboardDelta');e.textContent=`+${fmt(delta)}`;e.classList.remove('show');void e.offsetWidth;e.classList.add('show')}
async function openAbout(){try{const d=await api('/api/about');$('aboutTitle').textContent=d.title;$('aboutText').textContent=d.text;$('authorWords').textContent=d.author_words;$('donationBtn').href=d.donation_url||'#';$('contactSchoolBtn').href=d.contact_url||'https://t.me/lapiduser';$('contactSchoolBtn').textContent=d.contact_text||'Прислать фотографию своей школы → @lapiduser'}catch{}openSheet('about')}
async function refreshStats(){try{const d=await api('/api/stats');animateNumber($('statUsers'),d.total_visitors);animateNumber($('statActive'),d.active_users);animateNumber($('statClicks'),d.total_clicks);animateNumber($('statSchools'),d.schools_playing);animateNumber($('statCps'),d.cps_current);$('cpsAverage').textContent=`Среднее: ${String(d.cps_avg_5s).replace('.',',')}/с`;renderCpsChart(d.cps_last_5_seconds||[])}catch{}}
function renderCpsChart(values){const c=$('cpsChart');c.innerHTML='';const max=Math.max(1,...values);values.forEach((v,i)=>{const b=document.createElement('span');b.className=`cps-bar ${i===values.length-1?'current':''}`;b.style.height=`${Math.max(7,Math.round(Number(v)/max*100))}%`;b.title=`${v} кликов/с`;c.appendChild(b)})}
function openCaptchaGate(reset){if(!state.captchaEnabled)return;$('captchaGate').classList.add('open');$('captchaGate').setAttribute('aria-hidden','false');$('captchaStatus').textContent='Ожидание проверки…';$('clickLocked').classList.remove('hidden');if(reset&&state.turnstileWidgetId!==null&&window.turnstile){try{window.turnstile.reset(state.turnstileWidgetId)}catch{}state.turnstileToken=null}mountTurnstile()}
function closeCaptchaGate(back){if(back||state.clickEnabled){$('captchaGate').classList.remove('open');$('captchaGate').setAttribute('aria-hidden','true')}}
function mountTurnstile(){const key=window.BITVA_TURNSTILE_SITE_KEY||'';if(!key){$('captchaStatus').textContent='CAPTCHA не настроена';return}const go=()=>{if(!window.turnstile||state.turnstileWidgetId!==null)return;state.turnstileWidgetId=window.turnstile.render('#turnstileWidget',{sitekey:key,theme:'light',callback:onTurnstileToken,'expired-callback':()=>{state.clickEnabled=false;$('captchaStatus').textContent='Проверка истекла. Пройдите её снова.'},'error-callback':()=>{$('captchaStatus').textContent='Не удалось выполнить проверку.'}})};window.turnstile?go():setTimeout(go,600)}
async function onTurnstileToken(token){$('captchaStatus').textContent='Проверяем…';try{await api('/api/captcha/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});state.turnstileToken=token;state.clickEnabled=true;$('clickLocked').classList.add('hidden');$('captchaStatus').textContent='Готово. Рейтинг защищён.';setTimeout(()=>closeCaptchaGate(false),450)}catch(e){state.clickEnabled=false;$('captchaStatus').textContent=e.message||'Проверка не пройдена.';try{window.turnstile?.reset(state.turnstileWidgetId)}catch{}}}
(async()=>{const c=await api('/api/config').catch(()=>({turnstile_site_key:''}));window.BITVA_TURNSTILE_SITE_KEY=c.turnstile_site_key||'';await bootstrap()})()